name: SurvivalGames
description: SurvivalGames plugin for PocketMine-MP servers.
main: SurvivalGames\Main
version: 2.0
api: 3.14.0
load: STARTUP
website: https://github.com/IceCruelStuff/SurvivalGames

commands:
  sg:
    description: SurvivalGames main command. 
