name: SurvivalGames
author: Zeao
description: The Main SurvivalGames plugin, the official and soon may be bug free.
main: Zeao\Main
version: 2.0.0-BETA
api: [3.0.0, 4.0.0]
LOAD: STARTUP

commands:
    sg:
        description: SurvivalGames main command. 
